import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike Slim Shirt",
    slug: "nike-slim-shirt",
    image: "../images/p1.jpg",
    category: "Shirts",
    price: 120,
    brand: "Nike",
    countInStock: 10,
    description: "high quality product",
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: "Adidas Fit Shirt",
    slug: "Adidas-fit-shirt",
    category: "Shirts",
    image: "../images/p2.jpg",
    price: 250,
    countInStock: 20,
    brand: "Adidas",
    rating: 4.0,
    numReviews: 10,
    description: "High quality shirt",
  },
  {
    name: "Lacoste Free Pants",
    slug: "lacoste-free-pant",
    category: "Pants",
    image: "../images/p3.jpg",
    price: 25,
    countInStock: 15,
    brand: "Lacoste",
    rating: 4.5,
    numReviews: 14,
    description: "High quality product",
  },
  {
    name: "Nike Slim Pant",
    slug: "nike-slim-pant",
    category: "Pants",
    image: "../images/p4.jpg",
    price: 65,
    countInStock: 5,
    brand: "NIke",
    rating: 4.5,
    numReviews: 10,
    description: "High quality product",
  },
];